name: Incremental Gradle Build
on: workflow_dispatch
jobs:
  gradle_build:
    runs-on: macos-11
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble --debug
          build-root-directory: sample-mpp-lib